### PR TITLE
make paramvalf-run automatically write a log file (untested)

### PR DESCRIPTION
**Pull request by kostrzewa**
still need to see if this works as expected but I wanted to see if you agree with this or if we should make this optional somehow

### CODE REVIEW

**Comment by martin-ueding** [comment]
One disadvantage of this is the output buffering, it might buffer larger chunks in the pipe such that output is delayed.

Then I'd prefer an actual ISO date, so `date -Iseconds` would be preferred for a timestamp.

One can redirect the whole output of a shell script without having to wrap it into a function, but that is not so important.

Why would you want to have these logs? Like going back to see which failures one already had at some point?

**Comment by kostrzewa** [comment]
> One disadvantage of this is the output buffering, it might buffer larger chunks in the pipe such that output is delayed.

I've never seen that with tee to be honest.

> Then I'd prefer an actual ISO date, so `date -Iseconds` would be preferred for a timestamp.

Agreed on enabling automated tools to parse the datetime, but colons and pluses make the logs annoying to open on the console...

> One can redirect the whole output of a shell script without having to wrap it into a function, but that is not so important.
> 
> Why would you want to have these logs? Like going back to see which failures one already had at some point?

Even to just have logs in the first place without having to manually redirect the output (main problem here is to remember to do it) or having to wrap paralvamf-run in a script manually which would then have the same functionality.

When running the analysis in a screen session, it is quite nice to be able to go back to see what actually happened during the run if for some reason some of the expected output is missing even though there were no failures (this may happen due to R's treatment of `$member`, for example).

To not create so many versions of the log file, I would also be happy with "latest" and "previous" logs or something like that with a file existence check and automatic moving around. Even a single log file would be better than none.

**Comment by kostrzewa** [comment]
> One can redirect the whole output of a shell script without having to wrap it into a function, but that is not so important.

I don't want to have to do it manually and I definitely also want console output at the same time.

**Comment by martin-ueding** [comment]
I was just thinking of [this here](http://mywiki.wooledge.org/BashFAQ/106):

```bash
exec > >(tee mylog) 
```

Then the remainder of the script has its output to that logfile. But having a function does not really make it so much more complex. Also we can then have more control over the log, that might be nice.

**Pull request merged**
